logger_name: 'meetyou_auto'
log_file_name: 'meetyou_test.log'
backup_count: 5
console_output_level: 'INFO'
file_output_level: 'DEBUG'
formatter: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s'